# Generated by Django 3.2.9 on 2022-08-15 09:29

from django.db import migrations, models
import django.utils.timezone
import manager.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_serial', models.CharField(default=manager.models.generate_serial, max_length=255)),
                ('applicant_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_mname', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_area_code', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='phone')),
                ('mobile_area_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('apply_as', models.CharField(blank=True, max_length=100, null=True)),
                ('biz_location1', models.CharField(blank=True, max_length=100, null=True)),
                ('biz_location2', models.CharField(blank=True, max_length=100, null=True)),
                ('biz_city', models.CharField(blank=True, max_length=100, null=True)),
                ('biz_state', models.CharField(blank=True, max_length=100, null=True)),
                ('biz_zip_code', models.DateField(blank=True, null=True)),
                ('marketing_material', models.FileField(blank=True, default='', null=True, upload_to='uploads/')),
                ('marketing_information', models.FileField(blank=True, default='', null=True, upload_to='uploads/')),
                ('statement', models.CharField(blank=True, max_length=100, null=True)),
                ('statement_information', models.FileField(blank=True, default='', null=True, upload_to='uploads/')),
                ('been_financed', models.CharField(blank=True, max_length=100, null=True)),
                ('lender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('finance_was_for', models.CharField(blank=True, max_length=100, null=True)),
                ('demurrage', models.CharField(blank=True, max_length=100, null=True)),
                ('demurrage_dolla', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('project_gross_value', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'application_table',
                'db_table': 'application_table',
                'ordering': ('created_at',),
            },
        ),
    ]
